### ISSUE TITLE
Throwing exports not defined when there are no exports defined in the mdx frontmatter.

### ISSUE THREAD

**Issue by Christopher-Stevers** [conradludgate/nuxt-mdx#1]
### Replication
- Add nuxt-mdx to package.json and build-modules as per the readme instructions.
- create a post.mdx file in the pages directory with some text
- run yarn install and yarn dev
- go to /post in your browser. You should see a 500 error code saying exports is not defined.
### Work Around
Add at least one export to your post.mdx file ( I added export const layout = "post";)
If you'd like I can submit a pr on your readme just to mention this, its frustrating to attempt to use this be stuck on server errors. By the way, thanks for setting this up, its the first plugin I've found to make markdown work on Nuxt 3.

**Comment by conradludgate** [comment]
Interesting. I guess I didn't test for that scenario. Thanks for flagging it. I haven't used nuxt3 much yet (I think I'm sticking with React for now) but I can try get a patch out in a few days, unless you wanna give it a shot

**Comment by conradludgate** [comment]
Should be fixed. Let me know if you have any further problems
